### ISSUE TITLE
HTTPハンドラ内で`os.Exit`してはいけない

### ISSUE THREAD

**Issue by budougumi0617** [t0w4/go_tsumamigui_book_codes#2]
https://github.com/t0w4/go_tsumamigui_book_codes/blob/8b7982a5e860bace13b45e3f1ce76a06c1d16dd7/go_mysql/main.go#L35-L38

このような処理がいくつか書かれてますが、Webハンドラ内で`os.Exit`するとアプリが終了（瞬断）するのでエラーがクライアント側に返しません。エラーが出る状態のアプリに`curl`コマンドなどを実行してみれば、エラーレスポンスが帰らずサーバが終了するのがわかります。

**Comment by t0w4** [comment]
こちらもcloseします
